'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Calendar, Download, Share2, CheckCircle, Clock } from 'lucide-react';

interface CalendarDay {
  date: string;
  dayName: string;
  outfit: {
    topwear: string;
    bottomwear: string;
    accessories: string[];
    description: string;
    occasion: string;
    styling_tips: string[];
  };
  weather?: {
    temperature: number;
    condition: string;
    icon: string;
  };
}

export default function CalendarPage() {
  const router = useRouter();
  const [calendar, setCalendar] = useState<CalendarDay[]>([]);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [userPoints, setUserPoints] = useState(0);

  useEffect(() => {
    // Load user points
    const storedPoints = localStorage.getItem('userPoints');
    if (storedPoints) {
      setUserPoints(parseInt(storedPoints));
    }
  }, []);

  const generateCalendar = async () => {
    setGenerating(true);
    setError(null);

    try {
      // For demo purposes, create a mock calendar
      // In a real implementation, this would call the API with user's wardrobe
      const mockCalendar = generateMockCalendar();
      setCalendar(mockCalendar);
    } catch (error) {
      console.error('Error generating calendar:', error);
      setError('Failed to generate calendar. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const generateMockCalendar = (): CalendarDay[] => {
    const days: CalendarDay[] = [];
    const today = new Date();
    
    for (let i = 0; i < 10; i++) {
      const date = new Date(today);
      date.setDate(today.getDate() + i);
      
      const occasions = ['Work', 'Casual', 'Formal', 'Weekend', 'Date Night', 'Gym', 'Brunch', 'Meeting', 'Shopping', 'Relaxing'];
      const topwears = ['White Blouse', 'Blue Shirt', 'Black Sweater', 'Denim Jacket', 'Striped Top', 'Pink Blouse', 'Gray Hoodie', 'Red Cardigan', 'Floral Dress', 'Navy Polo'];
      const bottomwears = ['Black Pants', 'Blue Jeans', 'Gray Skirt', 'White Shorts', 'Black Dress Pants', 'Denim Skirt', 'Leggings', 'Khaki Pants', 'Maxi Skirt', 'Cargo Pants'];
      const accessories = ['Gold Earrings', 'Silver Watch', 'Leather Belt', 'Silk Scarf', 'Statement Necklace', 'Pearl Earrings', 'Leather Bag', 'Sunglasses', 'Hair Clip', 'Bracelet'];
      
      days.push({
        date: date.toISOString().split('T')[0],
        dayName: date.toLocaleDateString('en-US', { weekday: 'long' }),
        outfit: {
          topwear: topwears[i % topwears.length],
          bottomwear: bottomwears[i % bottomwears.length],
          accessories: [accessories[i % accessories.length], accessories[(i + 1) % accessories.length]],
          description: `A perfect ${occasions[i % occasions.length].toLowerCase()} look that combines style and comfort for your day ahead.`,
          occasion: occasions[i % occasions.length],
          styling_tips: [
            'Add a statement accessory to elevate the look',
            'Choose shoes that complement the occasion',
            'Layer with a jacket for versatility'
          ]
        },
        weather: {
          temperature: 18 + (i * 2),
          condition: ['Sunny', 'Partly Cloudy', 'Cloudy', 'Rainy'][i % 4],
          icon: '☀️'
        }
      });
    }
    
    return days;
  };

  const downloadCalendar = () => {
    const content = calendar.map(day => 
      `${day.date} (${day.dayName})
================

Outfit: ${day.outfit.description}
Topwear: ${day.outfit.topwear}
Bottomwear: ${day.outfit.bottomwear}
Accessories: ${day.outfit.accessories.join(', ')}

Occasion: ${day.outfit.occasion}

Styling Tips:
${day.outfit.styling_tips.map(tip => `• ${tip}`).join('\n')}

${day.weather ? `Weather: ${day.weather.temperature}°C, ${day.weather.condition}` : ''}

`
    ).join('\n\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `outfit-calendar-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const shareCalendar = async () => {
    const shareData = {
      title: 'My 10-Day Outfit Calendar - AuraSync',
      text: `Check out my personalized 10-day outfit calendar generated by AuraSync!`,
      url: window.location.href
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(
          `My 10-Day Outfit Calendar:\n\n${calendar.map(day => `${day.date}: ${day.outfit.description}`).join('\n')}`
        );
        alert('Calendar details copied to clipboard!');
      }
    } catch (error) {
      console.error('Error sharing calendar:', error);
    }
  };

  const getWeatherIcon = (condition: string) => {
    const conditions = condition.toLowerCase();
    if (conditions.includes('sunny') || conditions.includes('clear')) return '☀️';
    if (conditions.includes('cloudy') || conditions.includes('overcast')) return '☁️';
    if (conditions.includes('rain') || conditions.includes('drizzle')) return '🌧️';
    if (conditions.includes('snow')) return '❄️';
    if (conditions.includes('wind')) return '💨';
    return '🌤️';
  };

  if (generating) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="max-w-md mx-auto text-center p-8">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-500 mx-auto mb-6"></div>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Generating Your Calendar</h2>
          <p className="text-gray-600 mb-6">
            Our AI is creating your personalized 10-day outfit calendar...
          </p>
          <div className="flex items-center justify-center gap-2 text-sm text-gray-500">
            <Clock className="w-4 h-4" />
            This may take a few moments
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#251F1E]">
      <div className="max-w-6xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-4">
            <button
              onClick={() => router.back()}
              className="p-2 hover:bg-gray-200 rounded-full transition-colors"
            >
              <ArrowLeft className="w-6 h-6" />
            </button>
            <div>
              <h1 className="text-3xl font-bold text-white">Your 10-Day Outfit Calendar</h1>
              <p className="text-gray-600">Personalized styling plan for the next 10 days</p>
            </div>
          </div>
          
          <div className="flex gap-3">
            {calendar.length > 0 && (
              <>
                <button
                  onClick={downloadCalendar}
                  className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Download
                </button>
                <button
                  onClick={shareCalendar}
                  className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  Share
                </button>
              </>
            )}
            <button
              onClick={generateCalendar}
              className="flex items-center gap-2 px-6 py-3 bg-white/20 border text-white rounded-lg hover:bg-white/40 hover:to-pink-600 transition-all duration-200 shadow-lg"
            >
              <Calendar className="w-5 h-5" />
              Generate Calendar
            </button>
          </div>
        </div>

        {/* Calendar Grid */}
        {calendar.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-6">
            {calendar.map((day, index) => (
              <div
                key={day.date}
                className={`bg-white/30 rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-all duration-300 cursor-pointer ${
                  selectedDate === day.date ? 'ring-2 ring-blue-500' : ''
                }`}
                onClick={() => setSelectedDate(selectedDate === day.date ? null : day.date)}
              >
                {/* Date Header */}
                <div className="bg-white/10  text-white p-4">
                  <div className="text-sm font-medium">{day.dayName}</div>
                  <div className="text-lg font-bold">{new Date(day.date).getDate()}</div>
                  {day.weather && (
                    <div className="flex items-center gap-1 mt-2 text-sm">
                      <span>{getWeatherIcon(day.weather.condition)}</span>
                      <span>{day.weather.temperature}°C</span>
                    </div>
                  )}
                </div>

                {/* Outfit Preview */}
                <div className="p-4">
                  <div className="aspect-square bg-gradient-to-br from-gray-100 to-gray-200 rounded-lg mb-3 flex items-center justify-center">
                    <div className="text-center">
                      <div className="text-3xl mb-1">👗</div>
                      <div className="text-xs text-gray-600">Outfit</div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <h3 className="font-semibold text-gray-900 text-sm line-clamp-2">
                      {day.outfit.description}
                    </h3>
                    
                    <div className="text-xs text-gray-600">
                      <div className="flex items-center gap-1 mb-1">
                        <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                        {day.outfit.topwear}
                      </div>
                      <div className="flex items-center gap-1">
                        <span className="w-2 h-2 bg-green-500 rounded-full"></span>
                        {day.outfit.bottomwear}
                      </div>
                    </div>

                    <div className="flex items-center gap-1">
                      <span className="px-4 py-2 font-semibold bg-purple-200 border border-purple-400 text-purple-800 text-xs rounded-full">
                        {day.outfit.occasion}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <div className="text-6xl mb-4"></div>
            <h3 className="text-xl font-semibold text-gray-900 mb-2">No Calendar Generated</h3>
            <p className="text-gray-600 mb-6">Click Generate Calendar to create your personalized 10-day outfit plan.</p>
            <button
              onClick={generateCalendar}
              className="px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
            >
              Generate Calendar
            </button>
          </div>
        )}

        {/* Detailed View */}
        {selectedDate && (
          <div className="mt-8 bg-white rounded-xl shadow-lg p-6">
            {(() => {
              const day = calendar.find(d => d.date === selectedDate);
              if (!day) return null;

              return (
                <div>
                  <div className="flex items-center justify-between mb-6">
                    <h2 className="text-2xl font-bold text-gray-900">
                      {day.dayName}, {new Date(day.date).toLocaleDateString()}
                    </h2>
                    <button
                      onClick={() => setSelectedDate(null)}
                      className="p-2 hover:bg-gray-100 rounded-full transition-colors"
                    >
                      ✕
                    </button>
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Outfit Details */}
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900 mb-4">Outfit Details</h3>
                      <div className="space-y-4">
                        <div>
                          <h4 className="font-medium text-gray-900 mb-2">Description</h4>
                          <p className="text-gray-700">{day.outfit.description}</p>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                          <div>
                            <h4 className="font-medium text-gray-900 mb-2">Topwear</h4>
                            <p className="text-gray-700">{day.outfit.topwear}</p>
                          </div>
                          <div>
                            <h4 className="font-medium text-gray-900 mb-2">Bottomwear</h4>
                            <p className="text-gray-700">{day.outfit.bottomwear}</p>
                          </div>
                        </div>

                        {day.outfit.accessories.length > 0 && (
                          <div>
                            <h4 className="font-medium text-gray-900 mb-2">Accessories</h4>
                            <div className="flex flex-wrap gap-2">
                              {day.outfit.accessories.map((accessory, idx) => (
                                <span
                                  key={idx}
                                  className="px-3 py-1 bg-gray-100 text-gray-700 text-sm rounded-full"
                                >
                                  {accessory}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        <div>
                          <h4 className="font-medium text-gray-900 mb-2">Occasion</h4>
                          <span className="inline-block px-3 py-1 bg-blue-100 text-blue-800 text-sm rounded-full">
                            {day.outfit.occasion}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Styling Tips */}
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900 mb-4">Styling Tips</h3>
                      <div className="space-y-3">
                        {day.outfit.styling_tips.map((tip, idx) => (
                          <div key={idx} className="flex items-start gap-3">
                            <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                            <p className="text-gray-700">{tip}</p>
                          </div>
                        ))}
                      </div>

                      {day.weather && (
                        <div className="mt-6 p-4 bg-blue-50 rounded-lg">
                          <h4 className="font-medium text-gray-900 mb-2">Weather</h4>
                          <div className="flex items-center gap-2">
                            <span className="text-2xl">{getWeatherIcon(day.weather.condition)}</span>
                            <div>
                              <div className="font-medium">{day.weather.temperature}°C</div>
                              <div className="text-sm text-gray-600">{day.weather.condition}</div>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })()}
          </div>
        )}
      </div>
    </div>
  );
}
